### ISSUE TITLE
usepack command

### ISSUE THREAD

**Issue by Zeboot** [BlockWorlds/RegionalTextures#2]
a /usepack command needs to be added to allow a user to manually select one of the premade packs and use it, for example for use in the sandbox. Should toggle the player from the excludePlayers arraylist as well to prevent automatic switching

**Comment by Zeboot** [comment]
UPDATE : the permissions for /packs will have to be adjusted for this! At the moment there is one permission node for the entirety of the packs commands. We would need seperate permissions for the subcommands so people that want to use "/usepack" can also do "/packs list" to know what packs they can use

**Comment by AceDexter** [comment]
Is the /usepack command currently enabled for members?

**Comment by Zeboot** [comment]
"needs to be added" :P

**Comment by DukeVindzor** [comment]
I am working on this one by the way

**Comment by Zeboot** [comment]
should be done now, awaiting testing
