### ISSUE TITLE
change the "toggletextures" response text

### ISSUE THREAD

**Issue by Zeboot** [BlockWorlds/RegionalTextures#3]
the toggletextures text is still a bit... iffy. the reconnecting part needs to be reworded / removed and the "now no longer excluded" needs to be changed

**Comment by AceDexter** [comment]
IDEA:

Toggle On: "Server Textures now change per region"
Toggle Off: "Excluding player from Texture Pack regional changes"

**Comment by Zeboot** [comment]
implemented
