### ISSUE TITLE
Sandbox type overlays

### ISSUE THREAD

**Issue by Zeboot** [BlockWorlds/RegionalTextures#5]
Basically a way to create an overlay with a pack "null". This would make a region where your pack will never be changed, not even to the default one, so you can experiment with different packs

**Comment by Zeboot** [comment]
Ace is working on this one

**Comment by AceDexter** [comment]
As of now I have it setup to where I can do some testing on my local server. 

I'm able to create regions and apply packs to them using all the plugins (WorldEdit, WorldGuard, RegionalTextures) and although everything appears to be working, I'm unable to tell if applying overlays to the regions is working. Of course, when I step in one region to enter the next with different overlays applied to them respectfully, the server informs me [the player] that it is applying the pack "pack name" to you. However, it doesn't really appear to be changing anything at all...

Now, when I step out of my regions into the world with the default pack applied to it I get the message "Applying default pack to you!", however, what is different is I get a temporary pause and a quick loading indication "Downloading Resource Pack" and then an apparent change...
1. I may or may not be adding the resource pack to my regions correctly
   /packs add <name> <URL>
2. The URL I am using is incorrect
3. Or I do not have the plugin configured correctly...

Once I get this issue resolved I should be able to move on with my testing.

**Comment by Zeboot** [comment]
what URLs are you using?

**Comment by AceDexter** [comment]
Issue resolved:
1. I was using the incorrect URL (Well, what I needed was the compiled urls)
2. I was unaware of needing to update the overlays with /overlays update

**Comment by Zeboot** [comment]
NOW we can close it. fixed some issues and did proper testing

**Comment by AceDexter** [comment]
lol >.< Sorry! =\ xD
